---
- name: Check the number of specified disks per server
  assert:
    that: minio_mounts | length >= 4
    fail_msg: "At least four disks per server must be specified"
    success_msg: "A sufficient number of disks are specified"

- name: Erasure Coding configuration check
  assert:
    that:
      - minio_standard_ec_parity_drives | int >= 1
      - minio_standard_ec_parity_drives | int <= (minio_total_disks | int // 2)
      - minio_rrs_ec_parity_drives | int >= 1
      - minio_rrs_ec_parity_drives | int <= (minio_total_disks | int // 4)
    fail_msg: "Erasure Coding configuration does not meet fault tolerance requirements"
    success_msg: "Erasure Coding configuration meets fault tolerance requirements"


- name: Check MinIO Access Key and Secret Key requirements
  assert:
    that:
      - minio_root_user | length >= 3
      - minio_root_password | length >= 8
    fail_msg: "minio_root_user must be at least 3 characters long, minio_root_password must be at least 8 characters long"
    success_msg: "Access Key and Secret Key meet the requirements"