---
- name: Check the number of specified disks per server
  assert:
    that: minio_mounts | length >= 4
    fail_msg: "At least four disks per server must be specified"
    success_msg: "A sufficient number of disks are specified"


- name: Check MinIO Access Key and Secret Key requirements
  assert:
    that:
      - minio_root_user | length >= 3
      - minio_root_password | length >= 8
    fail_msg: "minio_root_user must be at least 3 characters long, minio_root_password must be at least 8 characters long"
    success_msg: "Access Key and Secret Key meet the requirements"