---
- name: Generate the MinIO envfile 
  template:
    src: "{{ role_path }}/templates/minio.env.j2"
    dest: /etc/default/minio

- name: Create the MinIO systemd 
  template:
    src: "{{ role_path }}/templates/minio.service.j2"
    dest: /etc/systemd/system/minio.service
  notify:
    - reload systemd
    - restart minio