---
- name: Generate the MinIO envfile 
  template:
    src: "minio.env.j2"
    dest: /etc/default/minio
  notify:
    - reload systemd
    - restart minio

- name: Create the MinIO systemd 
  template:
    src: "minio.service.j2"
    dest: /etc/systemd/system/minio.service
  notify:
    - reload systemd
    - restart minio