---
- name: Requirements verification
  import_tasks: check.yml

- name: Creating a MinIO user and group
  import_tasks: user.yml

- name: Installing and configuring mount points
  import_tasks: mount.yml

- name: Installing the MinIO binary file
  import_tasks: install.yml

- name: MinIO envfile and systemd configuration
  import_tasks: configure.yml