---
# TODO this task file

- name: MiniIO binary installation
  copy:
    src: "{{ role_path }}/files/minio"
    dest: "{{ minio_binary_path }}"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: '0755'