---
- name: Installing xfsprogs to work with XFS
  package:
    name: xfsprogs
    state: present

- name: Creating a mount point for MinIO data
  file:
    path: "{{ minio_data_dir }}{{ ansible_loop.index }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
  loop: "{{ minio_mounts }}"
  loop_control:
    extended: true

- name: Creating an XFS file system on disks
  filesystem:
    fstype: xfs
    dev: "{{ item }}"
  loop: "{{ minio_mounts }}"

- name: Mounting a disk to a mount point
  mount:
    path: "{{ minio_data_dir }}{{ ansible_loop.index }}"
    src: "{{ item }}"
    fstype: xfs
    opts: defaults,noatime
    state: mounted
  loop: "{{ minio_mounts }}"
  loop_control:
    extended: true

- name: Changing ownership of the mount points to MinIO user and group
  file:
    path: "{{ minio_data_dir }}{{ ansible_loop.index }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    recurse: yes
  loop: "{{ minio_mounts }}"
  loop_control:
    extended: true
